const FETCH_BLOGS = "FETCH_BLOGS";
const FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS";
const FETCH_BLOGS_FAIL = "FETCH_BLOGS_FAIL";

export default {
	FETCH_BLOGS,
	FETCH_BLOGS_SUCCESS,
	FETCH_BLOGS_FAIL
}